repository: vinayak19th/vinayak19th.github.io/
favicon: images/fav.ico``

# Personal info
name: Vinayak Sharma
title: Third Year, Computer Science & Engineering
email: vinayak1998th@Gmail.com
phone: "9994756433"
website: vinayak19th.github.io

darkmode: false

# Social links
#twitter_username: jekyllrb
github_username:  vinayak19th
stackoverflow_username: 8700517/vinayak-sharma
facebook_username: vinayak19th
instagram_username: stochastic_individual
linkedin_username: vinayaksha

# Additional icon links
#additional_links:
#- title: Link name
#  icon: Font Awesome brand icon name (eg. fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#  url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/picture.jpg
about_content: | # this will include new lines to allow paragraphs
  Student Researcher with a passion for the fields of <mark>Deep Learning</mark> & <mark>Quantum Computing</mark>.
  Currently the <mark>Head of Research, AI & Quantum Computing</mark> at [Next Tech Lab](https://nextech.io/) and Vice-Chairperson of 
  [ACM Student chapter](https://www.facebook.com/SRMACM/) at SRM IST. <br>
  I am proficient with :
  - Python 3.x and its common associated libraries (numpy, pandas, matplotlib, django)
  - [Tensorflow](https://www.tensorflow.org/), [cirq](https://cirq.readthedocs.io/en/stable/) and their combinational 
  library [Tensorflow Quantum](https://www.tensorflow.org/quantum). 
  - I also have some experience with deploying models using [tensorflow.js](https://www.tensorflow.org/js)

  I aim to pursue a masters degree in Computer Science with a focus on Quantum Machine Learning. 

# Projects Section
# projects_title: Projects #(Use this to override about projects section title)

# Experience Section
# experience_title: Experience #(Use this to override about experience section title)

# Education Section
# education_title: Education #(Use this to override about education section title)

# More Section
# more_title: A Little More About Me #(Use this to override about more section title)
more_content: | # this will include new lines to allow paragraphs
  
# Footer
footer_show_references: true

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
remote_theme : sproogen/modern-resume-theme

sass:
  sass_dir: _sass
  style: compressed
  load_paths:
        - _sass
        - node_modules


plugins:
  - jekyll-seo-tag

color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

markdown: kramdown
permalink: pretty

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]