repository: vinayak19th/vinayak19th.github.io/
# Personal info
name: Vinayak Sharma
title: MS in CS, Arizona State University
specialization : Machine Learning
email: vinayak1998th@Gmail.com
phone: +16025155883

# phone: "+91 9748939032" 
website: vinayak19th.github.io
darkmode: false

# Social links
#twitter_username: jekyllrb
github_username:  vinayak19th
#facebook_username: vinayak19th
google_scholar: https://scholar.google.com/citations?user=r763skMAAAAJ&hl=en
orcid: https://orcid.org/0009-0009-5633-4003
linkedin_username: vinayak19th
#use international format
whatsapp_number: "16025155883"
medium: vinayak1998th

resume: https://drive.google.com/file/d/1VAwintQeMaNDLtPgi3sElW3MMeGBvPQ_/view?usp=sharing
#Comment out to disable github stats
githubstats: True

# Additional icon links
#additional_links:P
#- title: Link name
#  icon: Font Awesome brand icon name (eg. fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#  url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
favicon: images/fav.ico
about_profile_image: https://www.gravatar.com/avatar/2302f2e8d1521c441894759ef96580b2?s=600


# Projects Section
# projects_title: Projects #(Use this to override about projects section title)

# Experience Section
experience_title: Professional Experience #(Use this to override about experience section title)

# Education Section
# education_title: Education #(Use this to override about education section title)

# More Section
# more_title: A Little More About Me #(Use this to override about more section title)
more_content: | # this will include new lines to allow paragraphs
  
# Footer
footer_show_references: true

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
remote_theme : sproogen/modern-resume-theme

sass:
  sass_dir: _sass
  style: compressed
  load_paths:
        - _sass
        - node_modules

plugins: ['jekyll/scholar','jekyll-seo-tag']

color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

markdown: kramdown
permalink: pretty

scholar:
  style: acm-sig-proceedings
  source: _data/
  bibliography: papers.bib
  sort_by: year
  order: descending
  bibliography_template: paper

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  "docs/",
  "README.md",
  ]